src/Entity/Folder.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FolderRepository")
 */
class Folder
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_created;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Track", mappedBy="folder")
     */
    private $tracks;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Band", inversedBy="folders")
     * @ORM\JoinColumn(nullable=true)
     */
    private $band;

    public function __construct()
    {
        $this->tracks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(?\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    /**
     * @return Collection|Track[]
     */
    public function getTracks(): Collection
    {
        return $this->tracks;
    }

    public function addTrack(Track $track): self
    {
        if (!$this->tracks->contains($track)) {
            $this->tracks[] = $track;
            $track->setFolder($this);
        }

        return $this;
    }

    public function removeTrack(Track $track): self
    {
        if ($this->tracks->contains($track)) {
            $this->tracks->removeElement($track);
            // set the owning side to null (unless already changed)
            if ($track->getFolder() === $this) {
                $track->setFolder(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->name;
    }

    public function getBand(): ?Band
    {
        return $this->band;
    }

    public function setBand(?Band $band): self
    {
        $this->band = $band;

        return $this;
    }
}

src/Form/FolderType.php
<?php

namespace App\Form;

use App\Entity\Folder;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FolderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, [
                'attr' => array(
                    'placeholder' => ' ',
                ),
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Folder::class,
        ]);
    }
}

src/Controller/FolderController.php
<?php

namespace App\Controller;

use App\Entity\Folder;
use App\Entity\Musician;
use App\Form\FolderType;
use App\Repository\BandRepository;
use App\Repository\FolderRepository;
use App\Repository\MusicianRepository;
use Cassandra\Time;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @Route("/folder")
 */
class FolderController extends AbstractController
{
    /**
     * @Route("/new", name="folder_new", methods={"GET","POST"})
     * @param Request $request
     * @param UserInterface|null $user
     * @param MusicianRepository $musicianRepository
     * @return Response
     * @throws \Exception
     */
    public function new(Request $request, ?UserInterface $user, MusicianRepository $musicianRepository, BandRepository $bandRepository): Response
    {
        $folder = new Folder();
        $dateTime = new DateTime();
        $form = $this->createForm(FolderType::class, $folder);
        $form->handleRequest($request);
        $musician = $musicianRepository->find($user->getId());

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $folder->setDateCreated($dateTime);
            $folder->setBand($bandRepository->findOneBy(['id' => $musician->getActiveBand()]));
            $entityManager->persist($folder);
            $entityManager->flush();

            return $this->redirectToRoute('open', ['id' => $folder->getId()]);
        }

        return $this->render('folder/new.html.twig', [
            'folder' => $folder,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="folder_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Folder $folder
     * @return Response
     */
    public function edit(Request $request, Folder $folder): Response
    {
        $form = $this->createForm(FolderType::class, $folder);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('folder_index');
        }

        return $this->render('folder/edit.html.twig', [
            'folder' => $folder,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="folder_delete", methods={"DELETE"})
     * @param Request $request
     * @param Folder $folder
     * @return Response
     */
    public function delete(Request $request, Folder $folder): Response
    {
        if ($this->isCsrfTokenValid('delete'.$folder->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($folder);
            $entityManager->flush();
        }

        return $this->redirectToRoute('folder_index');
    }
}

templates/folder/_delete_form.html.twig
<form method="post" action="{{ path('folder_delete', {'id': folder.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ folder.id) }}">
    <button class="btn">Delete</button>
</form>

templates/folder/_form.html.twig
{{ form_start(form) }}
<div class="name-form">
    {{ form_errors(form.name) }}
    {{ form_widget(form.name) }}
    <label for="{{ form.name.vars.id }}"
           class="{{ form.name.vars.required ? 'required' }} label-name">
        <span class="content-name">Folder name</span>
    </label>
</div>

    {{ form_widget(form) }}
    <button class="submit-button">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/folder/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Folder{% endblock %}

{% block body %}
    <h1>Edit Folder</h1>

    {{ include('folder/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('folder_index') }}">back to list</a>

    {{ include('folder/_delete_form.html.twig') }}
{% endblock %}

templates/folder/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Folder{% endblock %}

{% block body %}
<section class="music">
    <h2 class="new_track_title">Add a new Folder</h2>

    {{ include('folder/_form.html.twig') }}

    <a href="{{ path('home') }}">back to list</a>
</section>
{% endblock %}

templates/folder/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Folder{% endblock %}

{% block body %}
    <h1>Folder</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ folder.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ folder.name }}</td>
            </tr>
            <tr>
                <th>Date_created</th>
                <td>{{ folder.dateCreated ? folder.dateCreated|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('folder_index') }}">back to list</a>

    <a href="{{ path('folder_edit', {'id': folder.id}) }}">edit</a>

    {{ include('folder/_delete_form.html.twig') }}
{% endblock %}